// Словарь: русская строка → английская.
//
// Ключ — сам русский текст, см. пояснение в i18n.js. Ключи вида «ЭТАЖ {0}» —
// образцы для строк с подставленными числами: метка `{n}` держит место числа.
//
// Разделы идут в том же порядке, что и файлы игры, чтобы искать по знакомому
// месту, а не по алфавиту.

export const RU_EN = {

  // ───────────────────────────────── редкость (palette.js)
  'Обычное': 'Common',
  'Необычное': 'Uncommon',
  'Редкое': 'Rare',
  'Эпическое': 'Epic',
  'Легендарное': 'Legendary',
  'обычное': 'common',
  'необычное': 'uncommon',
  'редкое': 'rare',
  'эпическое': 'epic',
  'легендарное': 'legendary',

  // ───────────────────────────────── языки
  'Русский': 'Русский',
  'Язык': 'Language',

  // ───────────────────────────────── твари (enemies.js)
  'Слизень': 'Slime',
  'Матёрый слизень': 'Elder Slime',
  'Гоблин': 'Goblin',
  'Гоблин-лучник': 'Goblin Archer',
  'Волк': 'Wolf',
  'Лесной дух': 'Forest Wisp',
  'Вепрь': 'Boar',
  'Болотник': 'Bogling',
  'Плевун': 'Spitter',
  'Тинный волк': 'Silt Wolf',
  'Пиявка': 'Leech',
  'Ведьма топи': 'Marsh Witch',
  'Ледяной волк': 'Ice Wolf',
  'Ледяной призрак': 'Frost Wraith',
  'Мёрзлый стрелок': 'Frozen Archer',
  'Йети': 'Yeti',
  'Пещерная мышь': 'Cave Rat',
  'Бес': 'Imp',
  'Пепельный ворон': 'Ash Raven',
  'Тлеющий рыцарь': 'Ember Knight',
  'Магмовый голем': 'Magma Golem',
  'Гоблин-щитоносец': 'Goblin Shieldman',
  'Костяной страж': 'Bone Sentinel',
  'Мёрзлый латник': 'Frozen Legionary',
  'Гнилой вздутыш': 'Rotting Bloater',
  'Тлеющий шар': 'Ember Orb',
  'Шаман топи': 'Marsh Shaman',
  'Жрец культа': 'Cult Priest',
  'Скелет': 'Skeleton',
  'Культист': 'Cultist',
  'Тень': 'Shade',
  'Костяной голем': 'Bone Golem',
  'Древень Корнегрив': 'Rootmane the Ancient',
  'Тинная Карга': 'The Silt Hag',
  'Хранитель Стужи': 'Warden of the Frost',
  'Расплавленный Колосс': 'The Molten Colossus',

  // ── Пролом (третий акт)
  'Порождение пустоты': 'Voidspawn',
  'Ловчий разлома': 'Rift Stalker',
  'Бледный страж': 'Pale Warden',
  'Полый хор': 'Hollow Choir',
  'Зев': 'The Maw',
  'Бледный кузнец': 'Pale Smith',
  'Титан разлома': 'Rift Titan',
  'Сердце Пролома': 'The Breach Heart',
  'Лич Морвэн': 'Morvane the Lich',
  'Пасть Пустоты': 'The Void Maw',
  'Полый Государь': 'The Hollow King',
  'Тлеющая Вдова': 'The Ember Widow',
  'Корневой Страж': 'The Root Warden',
  'промах': 'miss',
  'сорвано': 'broken',

  // ───────────────────────────────── слоты (player.js)
  'Оружие': 'Weapon',
  'Доспех': 'Armor',
  'Шлем': 'Helm',
  'Кольцо': 'Ring',
  'Амулет': 'Amulet',
  'Умение 1': 'Skill 1',
  'Умение 2': 'Skill 2',
  'Умение 3': 'Skill 3',
  'Пассивка': 'Passive',
  'ОПЛОТ': 'BULWARK',

  // ───────────────────────────────── игровые сообщения (game.js)
  'ВЕЛОРИЯ': 'VELORIA',
  'вольный город · безопасная зона': 'free city · safe haven',
  'Как играть': 'How to play',
  'WASD или стрелки — ходить. Левая кнопка мыши — удар, Shift — рывок, Q — зелье. E — заговорить.':
    'WASD or arrows to move. Left mouse button attacks, Shift dashes, Q drinks, E talks.',
  'Веди пальцем по левой половине экрана — герой пойдёт туда. Кнопки справа: удар, умения, рывок, зелье.':
    'Drag on the left half of the screen to move. The buttons on the right: attack, skills, dash, potion.',
  'Поговори с капитаном Дрейном — он даст первое задание':
    'Speak with Captain Drayne — he has your first job',
  'с возвращением, искатель': 'welcome back, seeker',
  'Браузер не пустил в полный экран — попробуй F11':
    'The browser refused fullscreen — try F11',
  'Спуск закрыт, пока жив страж этажа': 'The stairs stay shut while the floor guardian lives',
  'Новый рекорд глубины: ': 'New depth record: ',
  'Бездна пройдена глубже: ': 'Abyss pushed deeper: ',
  'здесь кто-то ждёт': 'someone is waiting here',
  'безопасная зона': 'safe haven',
  'ФОКУС': 'FOCUS',
  'мимо': 'miss',
  'БЛОК': 'BLOCK',
  'ПОВЕРЖЕН': 'SLAIN',
  'Спуск глубже открыт': 'The way down is open',
  'Слот запечатан алтарём': 'The altar sealed that slot',
  'Слот умения пуст — вставь руну': 'Empty skill slot — socket a rune',
  'Не хватает маны': 'Not enough mana',
  'ЭХО': 'ECHO',
  'Нет зелий': 'No potions',
  'На этом этаже зелья мертвы': 'Potions are dead on this floor',
  'Здоровье полное': 'Health is full',
  ' действует': ' is already active',
  'Ты и так в городе': 'You are already in the city',
  'Свиток вспыхивает…': 'The scroll flares…',
  'БЛАГОСЛОВЕНИЕ ДРЕВНИХ': 'BLESSING OF THE ANCIENTS',
  '+35% урона на 90 сек': '+35% damage for 90s',
  '−35% получаемого урона на 90 сек': '−35% damage taken for 90s',
  'ЗАСАДА!': 'AMBUSH!',
  'лагерь ожил': 'the camp stirs',
  'Лагерь зачищен — награда твоя': 'Camp cleared — the spoils are yours',
  'Получено: ': 'Received: ',
  'Не хватает материалов': 'Not enough materials',
  'Рюкзак полон': 'Pack is full',
  'ВЫКОВАНО': 'FORGED',
  'Разобрано: ': 'Salvaged: ',
  'пусто': 'nothing',
  'Не хватает золота': 'Not enough gold',
  'ПЕРЕПЛАВЛЕНО': 'REFORGED',
  'Надень оружие': 'Equip a weapon first',
  'Дальше точить некуда': 'Nothing left to sharpen',
  'Нужно три оружия той же редкости': 'Three weapons of the same rarity are needed',
  'ЗАТОЧКА УДАЛАСЬ': 'SHARPENING HELD',
  'Веха: ': 'Milestone: ',
  'ЗАТОЧКА СОРВАЛАСЬ': 'SHARPENING FAILED',
  'откат к вехе +': 'rolled back to milestone +',
  'МЕТАЛЛ НЕ ВЫДЕРЖАЛ': 'THE METAL GAVE',
  'оружие рассыпалось': 'the weapon crumbled',
  'СЛИЯНИЕ': 'FUSION',
  'Куплено: ': 'Bought: ',
  ' золота': ' gold',
  'УРОВЕНЬ ': 'LEVEL ',
  'ЗАДАНИЕ ВЫПОЛНЕНО': 'QUEST COMPLETE',
  'Награда: ': 'Reward: ',
  'Открыть сундук': 'Open the chest',
  'Коснуться обелиска': 'Touch the obelisk',
  'Передохнуть у костра': 'Rest at the fire',
  'Закрыто: страж ещё жив': 'Locked: the guardian still lives',
  'Силы восстановлены': 'Strength restored',
  'Сундук открыт': 'Chest opened',
  'Слияние рун': 'Fuse runes',
  'Кузня': 'Forge',
  'Торговля': 'Trade',
  'Развитие': 'Attributes',
  'Сбросить очки (200з)': 'Respec (200g)',
  'Задания': 'Quests',
  'Открыть врата': 'Open the gates',
  'Уйти': 'Leave',
  'Рюкзак полон!': 'Pack is full!',
  'ур. ': 'lv. ',
  ' · берегись': ' · beware',
  'загрузка…': 'loading…',

  // ───────────────────────────────── загрузка (main.js)
  'подбираем палитру': 'mixing the palette',
  'высекаем камень и дерево': 'carving stone and timber',
  'вдыхаем жизнь в тварей': 'breathing life into beasts',
  'зажигаем факелы': 'lighting the torches',
  'разворачиваем карту…': 'unrolling the map…',

  // ───────────────────────────────── Бездна (abyss.js)
  'Здоровье героя': 'Hero health',
  'Урон врагов': 'Enemy damage',
  'Скорость врагов': 'Enemy speed',
  'Добыча и опыт': 'Loot and XP',
  'Порча · дыхание': 'Corruption · Breath',
  'Порча · хватка': 'Corruption · Grip',
  'Порча · жажда': 'Corruption · Thirst',
  'Порча · утроба': 'Corruption · Womb',
  'Порча · дно': 'Corruption · Floor',

  // ───────────────────────────────── крафт (craft.js)
  'Кожаный': 'Leather',
  'Бронзовый': 'Bronze',
  'Железный': 'Iron',
  'Стальной': 'Steel',
  'Златой': 'Gilded',
  'Аркановый': 'Arcane',
  'Драконий': 'Draconic',
  'Меч': 'Sword',
  'Топор': 'Axe',
  'Кинжал': 'Dagger',
  'Копьё': 'Spear',
  'Посох': 'Staff',
  'Лук': 'Bow',
  'Броня': 'Armor',
  'Украшения': 'Trinkets',
  'Зелья': 'Potions',
  'бонусный аффикс': 'a bonus affix',
  'ещё аффикс и закалка': 'another affix and tempering',
  'уникальное свойство': 'a unique property',
  'аффикс «': 'affix “',
  'свойство «': 'property “',
  'закалка': 'tempering',

  // ───────────────────────────────── модификаторы этажей (dungeon_mods.js)
  'Тишина': 'Silence',
  'Обычный этаж без особенностей.': 'An ordinary floor, nothing special.',
  'Полчище': 'Horde',
  'Врагов вдвое больше.': 'Twice as many enemies.',
  'Исступление': 'Frenzy',
  'Враги быстрее и бьют сильнее.': 'Enemies are faster and hit harder.',
  'Укрепление': 'Hardening',
  'У всех врагов броня против лёгких ударов.': 'Every enemy is armored against light hits.',
  'Мгла': 'Gloom',
  'Свет героя вдвое короче.': 'Your light reaches half as far.',
  'Голод': 'Hunger',
  'Зелья на этаже не действуют.': 'Potions do nothing on this floor.',
  'Алчность': 'Greed',
  'Золота и добычи втрое больше.': 'Three times the gold and loot.',
  'Хрупкость': 'Brittleness',
  'Ты получаешь вдвое больше урона.': 'You take double damage.',
  'Травля': 'The Hunt',
  'По этажу ходит отряд с аффиксами.': 'A pack of affixed elites roams the floor.',
  'Щедрость': 'Bounty',
  'Втрое больше сундуков.': 'Three times as many chests.',
  'Затишье': 'Lull',
  'Врагов меньше, но и награда скромнее.': 'Fewer enemies, and a thinner reward.',
  'Кровавый обет': 'Blood Oath',
  'Отдай пятую часть здоровья — заберёшь треть чужого.':
    'Give up a fifth of your health, take a third of theirs.',
  '+30% урона': '+30% damage',
  '−20% максимума здоровья': '−20% max health',
  'Пошлина боли': 'Toll of Pain',
  'Камень требует крови, а не золота.': 'The stone wants blood, not gold.',
  'эпическая руна': 'an epic rune',
  '−25% текущего здоровья': '−25% current health',
  'Проклятие алчности': 'Curse of Greed',
  'Золото здесь мертво. Сталь — нет.': 'Gold is dead here. Steel is not.',
  'предмет не ниже редкого, уровень +3': 'an item of rare or better, level +3',
  'половина золота': 'half your gold',
  'Печать тишины': 'Seal of Silence',
  'Замолчи — и услышишь больше.': 'Fall silent, and you will hear more.',
  '+60% опыта до выхода': '+60% XP until you leave',
  'третий слот умения запечатан': 'the third skill slot is sealed',
  'Железная кожа': 'Iron Skin',
  'Медленнее — значит целее.': 'Slower is safer.',
  '−25% получаемого урона': '−25% damage taken',
  '−15% скорости передвижения': '−15% movement speed',
  'Голодный камень': 'Hungry Stone',
  'Он ест зелья. Взамен даёт вампиризм.': 'It eats potions. In return it gives lifesteal.',
  '+10% вампиризма': '+10% lifesteal',
  'все зелья лечения из рюкзака': 'every healing potion in your pack',
  'Стремительный': 'Swift',
  'Бронированный': 'Armored',
  'Пылающий': 'Blazing',
  'Вампирский': 'Vampiric',
  'Исполинский': 'Giant',
  'Призрачный': 'Spectral',

  // ───────────────────────────────── названия оружия (items.js)
  'Ржавый меч': 'Rusted Sword',
  'Железный меч': 'Iron Sword',
  'Стальной клинок': 'Steel Blade',
  'Клинок стражи': 'Warden Blade',
  'Златой эсток': 'Gilded Estoc',
  'Аркановый клинок': 'Arcane Blade',
  'Драконий палаш': 'Draconic Broadsword',
  'Дровяной топор': 'Woodcutter Axe',
  'Бронзовый топор': 'Bronze Axe',
  'Секира': 'Battleaxe',
  'Боевая секира': 'War Axe',
  'Златая секира': 'Gilded Axe',
  'Руническая секира': 'Runed Axe',
  'Топор пепла': 'Axe of Ashes',
  'Обломок ножа': 'Broken Knife',
  'Бронзовый кинжал': 'Bronze Dagger',
  'Стилет': 'Stiletto',
  'Клык ночи': 'Nightfang',
  'Златой кинжал': 'Gilded Dagger',
  'Теневой клык': 'Shadowfang',
  'Кровавый клык': 'Bloodfang',
  'Ветвь друида': 'Druid Branch',
  'Бронзовый посох': 'Bronze Staff',
  'Посох ученика': 'Apprentice Staff',
  'Посох магистра': 'Magister Staff',
  'Златой скипетр': 'Gilded Scepter',
  'Аркановый посох': 'Arcane Staff',
  'Жезл Бездны': 'Abyssal Rod',
  'Самодельный лук': 'Crude Bow',
  'Охотничий лук': 'Hunting Bow',
  'Тисовый лук': 'Yew Bow',
  'Лук стражи': 'Warden Bow',
  'Златой лук': 'Gilded Bow',
  'Лук Звездопада': 'Starfall Bow',
  'Лук багровых ветров': 'Bow of Crimson Winds',
  'Заострённый кол': 'Sharpened Stake',
  'Бронзовое копьё': 'Bronze Spear',
  'Пика': 'Pike',
  'Алебарда': 'Halberd',
  'Златое копьё': 'Gilded Spear',
  'Копьё Бури': 'Spear of the Storm',
  'Копьё Расплава': 'Spear of the Melt',
  'Тряпьё странника': 'Wanderer Rags',
  'Кожаный доспех': 'Leather Armor',
  'Кольчуга': 'Chainmail',
  'Латы стражи': 'Warden Plate',
  'Златые латы': 'Gilded Plate',
  'Аркановая мантия': 'Arcane Robe',
  'Драконья броня': 'Draconic Mail',
  'Холщовая повязка': 'Linen Wrap',
  'Кожаный шлем': 'Leather Helm',
  'Железный шлем': 'Iron Helm',
  'Шлем стражи': 'Warden Helm',
  'Златой шлем': 'Gilded Helm',
  'Венец магистра': 'Magister Crown',
  'Шлем Колосса': 'Colossus Helm',
  'Медное кольцо': 'Copper Ring',
  'Бронзовое кольцо': 'Bronze Ring',
  'Серебряное кольцо': 'Silver Ring',
  'Кольцо стражи': 'Warden Ring',
  'Златое кольцо': 'Gilded Ring',
  'Кольцо Арканы': 'Ring of Arcana',
  'Кольцо Дракона': 'Dragon Ring',
  'Костяной амулет': 'Bone Amulet',
  'Бронзовый амулет': 'Bronze Amulet',
  'Серебряный оберег': 'Silver Charm',
  'Амулет стражи': 'Warden Amulet',
  'Златой амулет': 'Gilded Amulet',
  'Амулет Арканы': 'Amulet of Arcana',
  'Сердце Дракона': 'Dragon Heart',

  // повадки оружия
  'сбалансированный': 'balanced',
  'медленный, тяжёлый': 'slow, heavy',
  'быстрый, критует': 'fast, crits often',
  'длинный размах': 'long reach',
  '+сила магии': '+magic power',
  'стреляет издалека': 'strikes from afar',

  // приставки: все четыре родовые формы дают одно английское слово
  'Острый': 'Sharp', 'Острая': 'Sharp', 'Острое': 'Sharp', 'Острые': 'Sharp',
  'Тяжёлый': 'Heavy', 'Тяжёлая': 'Heavy', 'Тяжёлое': 'Heavy', 'Тяжёлые': 'Heavy',
  'Быстрый': 'Swift', 'Быстрая': 'Swift', 'Быстрое': 'Swift', 'Быстрые': 'Swift',
  'Каменный': 'Stone', 'Каменная': 'Stone', 'Каменное': 'Stone', 'Каменные': 'Stone',
  'Пылающая': 'Blazing', 'Пылающее': 'Blazing', 'Пылающие': 'Blazing',
  'Ледяной': 'Frozen', 'Ледяная': 'Frozen', 'Ледяное': 'Frozen', 'Ледяные': 'Frozen',
  'Ядовитый': 'Venomous', 'Ядовитая': 'Venomous', 'Ядовитое': 'Venomous', 'Ядовитые': 'Venomous',
  'Благословенный': 'Blessed', 'Благословенная': 'Blessed', 'Благословенное': 'Blessed', 'Благословенные': 'Blessed',
  'Звёздный': 'Starlit', 'Звёздная': 'Starlit', 'Звёздное': 'Starlit', 'Звёздные': 'Starlit',
  'Кровавый': 'Bloody', 'Кровавая': 'Bloody', 'Кровавое': 'Bloody', 'Кровавые': 'Bloody',
  'Древний': 'Ancient', 'Древняя': 'Ancient', 'Древнее': 'Ancient', 'Древние': 'Ancient',
  'Точный': 'Precise', 'Точная': 'Precise', 'Точное': 'Precise', 'Точные': 'Precise',
  'Закалённый': 'Tempered', 'Закалённая': 'Tempered', 'Закалённое': 'Tempered', 'Закалённые': 'Tempered',

  // окончания
  'силы': 'of Might',
  'стойкости': 'of Fortitude',
  'ловкости': 'of Agility',
  'мудрости': 'of Wisdom',
  'ярости': 'of Fury',
  'вампира': 'of the Vampire',
  'грома': 'of Thunder',
  'вечности': 'of Eternity',
  'охотника': 'of the Hunter',
  'бастиона': 'of the Bastion',

  // характеристики
  'Урон': 'Damage',
  'Защита': 'Defense',
  'Здоровье': 'Health',
  'Мана': 'Mana',
  'Сила': 'Strength',
  'Выносл.': 'Endur.',
  'Ловкость': 'Agility',
  'Разум': 'Mind',
  'Крит %': 'Crit %',
  'Крит.урон %': 'Crit dmg %',
  'Скорость %': 'Speed %',
  'Вампиризм %': 'Lifesteal %',
  'Реген/с': 'Regen/s',
  'Урон в секунду': 'Damage per second',
  'Сила магии': 'Magic power',
  'Поджиг': 'Burn',
  'Яд': 'Poison',
  'Замедление %': 'Slow %',

  // расходники и материалы
  'Малое зелье лечения': 'Minor Healing Potion',
  'Зелье лечения': 'Healing Potion',
  'Большое зелье лечения': 'Greater Healing Potion',
  'Малое зелье маны': 'Minor Mana Potion',
  'Зелье маны': 'Mana Potion',
  'Эликсир ярости': 'Elixir of Fury',
  'Эликсир камня': 'Elixir of Stone',
  'Свиток возврата': 'Scroll of Return',
  'Восстанавливает 45 HP.': 'Restores 45 HP.',
  'Восстанавливает 120 HP.': 'Restores 120 HP.',
  'Восстанавливает 300 HP.': 'Restores 300 HP.',
  'Восстанавливает 40 MP.': 'Restores 40 MP.',
  'Восстанавливает 110 MP.': 'Restores 110 MP.',
  '+35% урона на 22 сек.': '+35% damage for 22s.',
  '-35% получаемого урона на 22 сек.': '-35% damage taken for 22s.',
  'Мгновенно телепортирует в Велорию.': 'Teleports you to Veloria at once.',
  'Волчий клык': 'Wolf Fang',
  'Грубая шкура': 'Coarse Hide',
  'Слизистый сгусток': 'Slime Clot',
  'Тусклая эссенция': 'Dim Essence',
  'Сердце топи': 'Bog Heart',
  'Осколок льда': 'Ice Shard',
  'Тлеющий уголь': 'Smoldering Coal',
  'Костяная пыль': 'Bone Dust',
  'Рунное ядро': 'Rune Core',
  'Железная руда': 'Iron Ore',
  'Серебряная жила': 'Silver Vein',
  'Пучок трав': 'Herb Bundle',
  'Драконья чешуя': 'Dragon Scale',
  'Осколок пустоты': 'Void Shard',
  'Слеза Бездны': 'Abyss Tear',
  'Бледный пепел': 'Pale Ash',
  'Стекло разлома': 'Rift Glass',

  // ── легендарки и ковка Пролома
  'Створ': 'Breachmaker',
  'Три удара подряд по одному врагу ломают его щит на 4 секунды.':
    'Three hits in a row on the same enemy break its shield for 4 seconds.',
  'Шаг сквозь': 'Stepthrough',
  'Рывок оставляет разлом: враги рядом получают урон и замедляются.':
    'Your dash leaves a rift: nearby enemies take damage and are slowed.',
  'Пустотная кожа': 'Voidskin',
  'Выбросы пустоты не жгут: урон от опасностей местности вдвое меньше.':
    'Void vents do not burn you: damage from terrain hazards is halved.',
  'Верный глаз': 'True Eye',
  'Уклонение врага не работает против вас чаще, чем раз в две секунды.':
    'An enemy cannot dodge you more than once every two seconds.',
  'Осколок Сердца': 'Heartshard',
  'Каждое убийство в Проломе гасит ближайший выброс пустоты на 6 секунд.':
    'Every kill in the Breach quiets the nearest void vent for 6 seconds.',
  'СТВОР': 'BREACHED',
  'Ковка Пролома даёт свойство, которое выберешь. Стекло разлома снимают с тех, кто ковал.':
    'Breach forging grants the property you pick. Rift glass is taken off those who forged.',
  'ТИХО': 'QUIET',
  'Настой пустоты': 'Void Draught',
  'Эликсир бледного': 'Pale Elixir',
  'Руна: ': 'Rune: ',
  'Материал. Продаётся торговцам, нужен для заданий.':
    'Material. Sells to merchants, needed for quests.',

  // ───────────────────────────────── подсказки (lessons.js)
  'Связка из трёх ударов': 'The three-hit combo',
  'Третий удар подряд бьёт тяжело: пробивает щиты и броню. Не спеши — держи ритм.':
    'The third hit in a row lands heavy: it breaks shields and armor. Do not rush — keep the rhythm.',
  'Очки развития': 'Attribute points',
  'За уровень дают 3 очка. Вложить — у наставника в Велории, клавиша C покажет, куда они ушли.':
    'Each level grants 3 points. Spend them at the trainer in Veloria; press C to see where they went.',
  'Умения — это руны': 'Skills are runes',
  'Руна вставляется в слот F, R или G. Оружие ни на что не влияет: набор умений — твой выбор, а не класс.':
    'A rune goes into slot F, R or G. Your weapon changes nothing: the skill set is your choice, not a class.',
  'Пассивная руна': 'Passive rune',
  'Слот пассивки один. Она работает всегда и часто решает больше, чем третье активное умение.':
    'There is one passive slot. It always works, and often matters more than a third active skill.',
  'Щитоносцы держат фронт': 'Shieldmen hold the front',
  'Щит гасит удары спереди и доворачивается с задержкой. Заходи сбоку — или ломай третьим ударом связки.':
    'A shield eats hits from the front and turns with a delay. Come from the side — or break it with the third hit of the combo.',
  'Стихийные метки': 'Elemental marks',
  'Поджиг, яд, обморожение и разряд висят на враге значками. Две метки вместе дают реакцию — схема во вкладке «Стихии».':
    'Burn, poison, chill and shock sit on the enemy as icons. Two marks together make a reaction — see the Elements tab.',
  'Реакция стихий': 'Elemental reaction',
  'Вторая метка не легла поверх первой — они схлопнулись. У каждой пары свой эффект и своя роль в бою.':
    'The second mark did not stack on the first — they collapsed. Every pair has its own effect and its own role in a fight.',
  'Элита с аффиксом': 'Affixed elites',
  'Аффикс меняет не только числа: бронированный режет лёгкие удары, призрачный уклоняется. Смотри, с кем связался.':
    'An affix changes more than numbers: armored cuts light hits, spectral dodges. Look at what you picked a fight with.',
  'Редкость — это аффиксы': 'Rarity means affixes',
  'Чем выше редкость, тем больше аффиксов сверх базы. Наведи курсор в инвентаре — сравнение с надетым покажет стрелки.':
    'The higher the rarity, the more affixes above the base. Hover in the pack — the comparison with your gear shows arrows.',
  'Кузня Борина': 'Borin’s forge',
  'Четыре вкладки: ковка, заточка, переплавка, разбор. Ненужную вещь выгоднее разобрать, чем продать.':
    'Four tabs: forge, sharpen, reforge, salvage. An unwanted item is worth more salvaged than sold.',
  'Заточка — это риск': 'Sharpening is a gamble',
  'Три оружия той же редкости сгорают всегда. Пока не взята веха +3, при неудаче гибнет и само оружие.':
    'Three weapons of the same rarity always burn. Until milestone +3 is reached, a failure destroys the weapon too.',
  'Вехи заточки': 'Sharpening milestones',
  'На +3 и +5 оружие получает лишний аффикс, на +7 — легендарное свойство. С +3 провал уже не рассыпает оружие, а откатывает.':
    'At +3 and +5 the weapon gains an extra affix, at +7 a legendary property. From +3 on, a failure rolls it back instead of destroying it.',
  'Комплект': 'Set',
  'Вещи одного комплекта помечены уголком в слоте. Две части дают бонус, четыре — второй, сильнее.':
    'Items of one set are marked with a corner in the slot. Two pieces give a bonus, four give a second, stronger one.',
  'Легендарка — это свойство': 'A legendary is a property',
  'У легендарных вещей главное не числа, а срабатывание. Описание — в карточке предмета оранжевым.':
    'On legendary items the numbers are not the point — the trigger is. The description is in orange on the item card.',
  'Двери подземелья': 'The dungeon doors',
  'Модификатор этажа выбираешь сам и изменить его потом нельзя. Риск поднимает добычу и опыт.':
    'You choose the floor modifier yourself, and it cannot be changed afterwards. Risk raises loot and XP.',
  'Проклятый алтарь': 'The cursed altar',
  'Алтарь всегда что-то забирает. Дар держится до выхода на поверхность — и исчезает вместе с забегом.':
    'The altar always takes something. The gift lasts until you surface — and dies with the run.',
  'За 25-м этажом растёт Порча: она сжимает твою шкалу жизни и усиливает врагов. Снять её нельзя — только подняться.':
    'Past floor 25 Corruption grows: it squeezes your health bar and strengthens enemies. It cannot be lifted — only climbed out of.',
  'Рекорд глубины': 'Depth record',
  'Рекорд хранится отдельно от сохранения: новая игра его не стирает. Он виден на титульном экране.':
    'The record is kept apart from the save: a new game does not erase it. It shows on the title screen.',

  // ───────────────────────────────── отряды (packs.js)
  'дозор': 'patrol',
  'застава': 'outpost',
  'ватага': 'warband',
  'свора': 'pack',
  'ковен': 'coven',
  'мины': 'minefield',
  'громилы': 'bruisers',
  'одиночка': 'loner',

  // ───────────────────────────────── реакции (reactions.js)
  'Горение': 'Burning',
  'Обморожение': 'Chill',
  'Отравление': 'Poisoned',
  'Разряд': 'Shock',
  'Ослепление': 'Blinded',
  'Разъедание': 'Corrosion',
  'РАЗЪЕДАНИЕ': 'CORROSION',
  'Сильный яд и −30% защиты на 6 сек.': 'Heavy poison and −30% defense for 6s.',
  'Проводимость': 'Conduction',
  'ПРОВОДИМОСТЬ': 'CONDUCTION',
  'Разряд по трём ближайшим врагам, метка передаётся.':
    'Shock leaps to the three nearest enemies, carrying the mark.',
  'Пар': 'Steam',
  'ПАР': 'STEAM',
  'Облако пара: враги внутри не стреляют и не колдуют.':
    'A cloud of steam: enemies inside cannot shoot or cast.',
  'Раскол': 'Shatter',
  'РАСКОЛ': 'SHATTER',
  'удар': 'a hit',
  'Тяжёлый удар по обмороженному бьёт вдвое сильнее.':
    'A heavy hit on a chilled target lands twice as hard.',

  // ───────────────────────────────── умения (skills.js)
  'физический': 'physical',
  'огонь': 'fire',
  'лёд': 'ice',
  'яд': 'poison',
  'аркана': 'arcane',
  'свет': 'light',
  'Вихрь клинков': 'Blade Vortex',
  'Круговой удар по всем вокруг с сильным отбросом.':
    'A sweeping strike at everything around you, with a hard knockback.',
  'Раскол земли': 'Earthsplitter',
  'Тяжёлый удар перед собой, волна вешает обморожение на уцелевших.':
    'A heavy blow ahead of you; the wave chills whatever survives.',
  'Сотрясение': 'Concussion',
  'Удар оземь: оглушает всех вокруг на 1,4 сек.': 'A slam into the ground: stuns everything around for 1.4s.',
  'Теневой рывок': 'Shadow Dash',
  'Рывок сквозь врагов: неуязвимость и гарантированный крит.':
    'A dash straight through enemies: invulnerable, and the hit always crits.',
  'Пронзание': 'Impale',
  'Длинный колющий выпад по прямой.': 'A long thrusting lunge in a straight line.',
  'Аркановый залп': 'Arcane Volley',
  'Три самонаводящихся снаряда, пробивают цель насквозь. Вешают разряд.':
    'Three homing bolts that punch clean through. They apply shock.',
  'Ливень стрел': 'Arrow Rain',
  'Веер из пяти стрел, каждая пробивает одну цель.': 'A fan of five arrows, each piercing one target.',
  'Цепная молния': 'Chain Lightning',
  'Молния прыгает по четырём целям, слабея на каждой. Вешает разряд.':
    'Lightning jumps across four targets, weakening on each. Applies shock.',
  'Стена огня': 'Wall of Fire',
  'Полоса пламени горит 5 сек и поджигает всех, кто в неё войдёт.':
    'A line of flame burns for 5s and ignites anything that walks in.',
  'Ледяная новая': 'Frost Nova',
  'Кольцо холода: урон и сильное замедление на 4 сек.': 'A ring of cold: damage and a hard slow for 4s.',
  'Ядовитое облако': 'Venom Cloud',
  'Облако едкого газа на 6 сек: постоянный урон и отравление.':
    'A cloud of caustic gas for 6s: steady damage and poison.',
  'Слово исцеления': 'Word of Healing',
  'Восстанавливает 28% здоровья и снимает горение и яд.': 'Restores 28% health and clears burning and poison.',
  'Барьер': 'Barrier',
  'Щит поглощает урон, равный 25% здоровья, в течение 10 сек.':
    'A shield absorbs damage equal to 25% of your health, for 10s.',
  'Барьер: ': 'Barrier: ',
  'Шипы': 'Thorns',
  'Отражает {v}% урона, полученного в ближнем бою.': 'Reflects {v}% of the damage taken in melee.',
  'Разгон': 'Momentum',
  'После убийства +{v}% скорости на 3 сек.': 'After a kill, +{v}% speed for 3s.',
  'Жажда крови': 'Bloodthirst',
  'Ниже 40% здоровья: +{v}% вампиризма.': 'Below 40% health: +{v}% lifesteal.',
  'Сосредоточение': 'Focus',
  'Откат умений короче на {v}%.': 'Skill cooldowns are {v}% shorter.',
  'Берсерк': 'Berserk',
  'До +{v}% урона тем сильнее, чем меньше здоровья.': 'Up to +{v}% damage, the lower your health.',
  'Страж': 'Warden',
  'Урон в ближнем бою по тебе слабее на {v}%.': 'Melee damage against you is {v}% weaker.',
  'Проворство': 'Nimbleness',
  'Откат рывка короче на {v}%.': 'Dash cooldown is {v}% shorter.',
  'Поток арканы': 'Arcane Flow',
  'Каждое убийство возвращает {v} маны.': 'Every kill returns {v} mana.',
  'Пирокинез': 'Pyrokinesis',
  'По горящим целям урон выше на {v}%.': 'Damage against burning targets is {v}% higher.',
  'Ледяное сердце': 'Frozen Heart',
  'По обмороженным шанс крита выше на {v}%.': 'Crit chance against chilled targets is {v}% higher.',
  'Токсиколог': 'Toxicologist',
  'Твой яд и разъедание тикают на {v}% чаще.': 'Your poison and corrosion tick {v}% more often.',
  'Катализатор': 'Catalyst',
  'Реакции стихий сильнее на {v}%.': 'Elemental reactions are {v}% stronger.',
  'Резонанс': 'Resonance',
  'Каждая реакция срезает {v} десятых секунды с откатов.':
    'Every reaction shaves {v} tenths of a second off your cooldowns.',

  // ───────────────────────────────── легендарки и комплекты (uniques.js)
  'Громобой': 'Thunderstrike',
  'Каждый третий удар бьёт цепной молнией по трём целям.':
    'Every third hit calls chain lightning across three targets.',
  'Пожиратель': 'Devourer',
  'Каждое убийство восстанавливает 5% здоровья.': 'Every kill restores 5% of your health.',
  'Раскалыватель': 'Splitter',
  'Критический удар выпускает четыре осколка.': 'A critical hit throws off four splinters.',
  'Пепельный шаг': 'Ashen Step',
  'Рывок оставляет за собой горящий след.': 'Your dash leaves a burning trail.',
  'Получив урон, раз в 6 сек бьёт ледяной волной вокруг.':
    'When struck, once every 6s it lashes out with a wave of ice.',
  'Оплот': 'Bulwark',
  'Раз в 9 сек первый удар по тебе поглощается полностью.':
    'Once every 9s, the first hit against you is absorbed entirely.',
  'Венец бури': 'Storm Crown',
  'Умения на 30% сильнее, но стоят на 25% больше маны.':
    'Skills are 30% stronger, but cost 25% more mana.',
  'Око сосредоточения': 'Eye of Focus',
  'Раз в 7 сек следующий удар — гарантированный крит двойной силы.':
    'Once every 7s, your next hit is a guaranteed crit at double force.',
  'Кольцо эха': 'Ring of Echoes',
  '22% шанс, что умение не уйдёт в откат.': '22% chance a skill does not go on cooldown.',
  'Печать жнеца': 'Reaper’s Seal',
  'Каждый восьмой убитый враг взрывается.': 'Every eighth enemy you kill explodes.',
  'Клеймо стужи': 'Brand of Frost',
  'Каждый удар вешает обморожение — раскол и пар доступны без рун.':
    'Every hit applies chill — shatter and steam work without runes.',
  'Пепельный мор': 'Ashen Plague',
  'Смерть горящего врага поджигает всех рядом.': 'A burning enemy’s death ignites everything nearby.',
  'Ледолом': 'Icebreaker',
  'Раскол по обмороженной цели бьёт вдвое сильнее.': 'Shatter on a chilled target hits twice as hard.',
  'Громоотвод': 'Lightning Rod',
  'Проводимость цепляет на три цели больше.': 'Conduction catches three more targets.',
  'Полое сердце': 'Hollow Heart',
  'Порча Бездны отнимает вдвое меньше здоровья.': 'Abyssal Corruption takes half as much health.',
  'Ненасытный': 'Insatiable',
  'Каждое убийство прибавляет +2% урона до конца этажа.':
    'Every kill adds +2% damage until the floor ends.',
  'Взгляд Бездны': 'Gaze of the Abyss',
  'Пропущенный удар с шансом 25% накладывает на бьющего все четыре метки.':
    'A hit you take has a 25% chance to put all four marks on the attacker.',
  'ВЗГЛЯД': 'GAZE',
  'Страж Велории': 'Warden of Veloria',
  '+16 защиты': '+16 defense',
  '−18% получаемого урона': '−18% damage taken',
  'Облачение Арканиста': 'Arcanist’s Vestments',
  '+45 маны': '+45 mana',
  '−20% отката умений': '−20% skill cooldown',
  'Снаряжение Ловчего': 'Hunter’s Kit',
  '+8% крит. шанса': '+8% crit chance',
  '+12% скорости, +30% крит. урона': '+12% speed, +30% crit damage',
  'Драконья кладка': 'Dragon Clutch',
  '+20 урона': '+20 damage',
  '+9% вампиризма': '+9% lifesteal',

  // ───────────────────────────────── HUD
  'ур.': 'lv.',
  'ЯРОСТЬ': 'FURY',
  'КАМЕНЬ': 'STONE',
  'ГОРИТ': 'BURNING',
  'ЯД': 'POISON',
  'ХОЛОД': 'CHILL',
  'ЛКМ': 'LMB',
  'Удар': 'Attack',
  'ПКМ': 'RMB',
  'Рывок': 'Dash',
  'Зелье': 'Potion',
  'ЗАДАНИЯ': 'QUESTS',

  // ───────────────────────────────── задания (quests.js)
  'Первая кровь': 'First Blood',
  'Слизни расползлись по опушке Изумрудного леса. Проредите их — это твой вступительный взнос в гильдию.':
    'Slimes have spread across the edge of the Emerald Wood. Thin them out — consider it your entrance fee to the guild.',
  'Клыки для кузни': 'Fangs for the Forge',
  'Борину нужны волчьи клыки — говорит, из них выходит славная рукоять. Принеси четыре.':
    'Borin wants wolf fangs — says they make a fine grip. Bring four.',
  'Зелёная угроза': 'The Green Menace',
  'Гоблины обнаглели и ставят засады у тропы. Убей десятерых — пусть подумают дважды.':
    'Goblins have grown bold and lay ambushes by the path. Kill ten — let them think twice.',
  'Корень зла': 'The Root of It',
  'В глубине леса пробудился Древень Корнегрив. Пока он жив, лес не успокоится.':
    'Deep in the wood, Rootmane the Ancient has woken. While he lives, the forest will not settle.',
  'Дорога в топь': 'Road to the Marsh',
  'Врата в Пепельную топь открыты. Ступи туда и вернись живым — уже достижение.':
    'The gate to the Ashen Marsh stands open. Step through and come back alive — that alone is something.',
  'Сердца топи': 'Hearts of the Marsh',
  'Сельвину нужны сердца болотных тварей. Не спрашивай зачем. Шесть штук.':
    'Selvin needs the hearts of marsh beasts. Do not ask why. Six of them.',
  'Ниже уровня земли': 'Below Ground',
  'Спустись в Катакомбы Велории до пятого этажа. Там что-то шевелится, и это не крысы.':
    'Descend into the Catacombs of Veloria to the fifth floor. Something stirs down there, and it is not rats.',
  'Карга не ждёт': 'The Hag Will Not Wait',
  'Тинная Карга варит что-то в глубине топи. Останови её, пока варево не дошло до города.':
    'The Silt Hag is brewing something deep in the marsh. Stop her before the brew reaches the city.',
  'На десятом этаже катакомб сидит лич. Он был человеком. Теперь — задача.':
    'A lich sits on the tenth floor of the catacombs. He was a man once. Now he is a job.',
  'Мёрзлый кряж': 'The Frozen Ridge',
  'Севернее — Мёрзлый кряж. Холод там убивает медленнее, чем его обитатели.':
    'North lies the Frozen Ridge. The cold there kills slower than what lives in it.',
  'Осколки стужи': 'Shards of Cold',
  'Мире нужны осколки льда для закалки доспехов. Восемь — и получишь один из них.':
    'Mira needs ice shards to temper armor. Eight, and one of them is yours.',
  'Ледяной страж кряжа не пропускает никого дальше перевала. Значит, пойдём через него.':
    'The ridge’s frost guardian lets no one past the pass. So we go through him.',
  'Трещины': 'The Cracks',
  'В кряже пошли трещины, и лезущие оттуда твари слишком уж разные. Пять таких голов — Дрейн хочет посмотреть на них сам.':
    'Cracks have opened in the ridge, and what crawls out of them is far too varied. Five such heads — Drayne wants a look himself.',
  'Что-то поднимается': 'Something Is Rising',
  'Спустись в катакомбы до двенадцатого этажа. Каменщики говорят: кладка там не наша. Значит, чья-то.':
    'Go down to the twelfth floor of the catacombs. The masons say the stonework there is not ours. So it is someone’s.',
  'Тлеющая пустошь': 'The Smoldering Waste',
  'Пролом': 'The Breach',
  'опасность: за гранью': 'danger: beyond measure',
  'Последние врата ведут в пепел и лаву. Обратной дороги никто не обещал.':
    'The last gate leads into ash and lava. Nobody promised a way back.',
  'То, что ходит по пустоши, когда-то было горой. Свали её обратно.':
    'What walks the waste was once a mountain. Put it back down.',
  'Колосс был не последним': 'The Colossus Was Not the Last',
  'Гора свалена, а трещины не закрылись. Дрейн просит спуститься на двадцатый этаж и посчитать, сколько их там.':
    'The mountain is down, and the cracks have not closed. Drayne asks you to reach floor twenty and count how many there are.',
  'Проба на пустоту': 'A Test for Void',
  'Сельвин перестал шутить. Ему нужны пять осколков пустоты — говорит, они не отражают свет, и это не свойство камня.':
    'Selvin has stopped joking. He wants five void shards — says they reflect no light, and that is not a property of stone.',
  'Хор внизу': 'The Choir Below',
  'Тварей под аффиксами стало столько, что гильдия перестала считать. Восемь голов — просто чтобы выдохнуть.':
    'There are so many affixed beasts now that the guild stopped counting. Eight heads — just to breathe.',
  'Порог': 'The Threshold',
  'Хранитель врат говорит: за двадцать пятым этажом воздух другой. Дойди до двадцать шестого и вернись — если сможешь.':
    'The gatekeeper says the air is different past floor twenty-five. Reach twenty-six and come back — if you can.',
  'Слёзы': 'Tears',
  'Пять Слёз Бездны. Сельвин называет их так не из красоты: в тепле они мокнут, и вода солёная.':
    'Five Abyss Tears. Selvin does not call them that for beauty: in warmth they weep, and the water is salt.',
  'Первый из тех, кто сторожит глубину. Он не охраняет сокровище — он не пускает наверх.':
    'The first of those who keep the deep. He guards no treasure — he keeps you from climbing out.',
  'Второй страж разговаривает. Дрейн просил передать: не отвечай ему.':
    'The second guardian talks. Drayne asked me to tell you: do not answer it.',
  'Дно, которого нет': 'A Floor That Is Not There',
  'Сорок пятый этаж. Дальше гильдия карт не рисует: Бездна оказалась не местом и не тварью, а направлением. Спускаться можно всегда — вопрос лишь в том, кто вернётся.':
    'Floor forty-five. The guild draws no maps past it: the Abyss turned out to be neither a place nor a beast, but a direction. You can always go down — the only question is who comes back.',

  // ── акт III: Пролом
  'Дрейн больше ничего не просит посчитать. Земля к востоку разошлась, и оттуда идут не твари, а свет. Дойди и посмотри сам.':
    'Drayne has nothing left to count. The ground to the east has come apart, and what comes out of it is not beasts but light. Go and see for yourself.',
  'Земля тоже кусается': 'The Ground Bites Too',
  'Хранитель врат говорит коротко: у разломов не стой. Порождений там столько, что двадцать голов — это разведка, а не работа.':
    'The Gatekeeper puts it briefly: do not stand near the rifts. There are so many voidspawn that twenty heads is scouting, not work.',
  'Шесть горстей пепла из Пролома. Сельвин просит собирать не с земли, а с тварей: то, что лежит, уже мертво дважды.':
    'Six handfuls of ash from the Breach. Selvin wants it taken off the beasts, not off the ground: what lies there is already twice dead.',
  'Ловчие': 'Stalkers',
  'Они уходят от удара чаще, чем попадают под него, и заходят со спины. Четырнадцать — и гильдия перестанет терять разведчиков.':
    'They slip a blow more often than they take one, and they come from behind. Fourteen, and the guild stops losing scouts.',
  'Щит без лица': 'A Shield With No Face',
  'Бледные стражи держат щит спереди и не устают. Десять голов — но заходить придётся иначе, чем ты привык.':
    'Pale wardens hold the shield in front and never tire. Ten heads — but you will have to come at them some other way than the one you know.',
  'Хор, который не поёт': 'The Choir That Does Not Sing',
  'Полый хор бьёт по звуку и замедляет всё, до чего дотянется. Двенадцать — Сельвин хочет знать, замолчат ли остальные.':
    'The hollow choir strikes by sound and slows everything it reaches. Twelve — Selvin wants to know whether the rest go quiet.',
  'Четыре куска стекла. Оно растёт только на тех, кто ковал в Проломе, и снимать его надо с них.':
    'Four pieces of glass. It grows only on those who forged in the Breach, and it has to be taken off them.',
  'Титаны': 'Titans',
  'Их не сдвинуть и не обойти. Гильдия просит троих — и просит вернуться, а не победить любой ценой.':
    'They cannot be moved and cannot be walked around. The guild asks for three — and asks you to come back, not to win at any cost.',
  'Оттуда, где нет дна': 'From Where There Is No Floor',
  'Хранитель просит спуститься на пятьдесят пятый и посмотреть вверх. Он думает, что Пролом и Бездна — это одно и то же место с двух сторон.':
    'The Gatekeeper asks you to go down to floor fifty-five and look up. He thinks the Breach and the Abyss are the same place seen from two sides.',
  'Оно не сторожит и не нападает первым — оно держит разлом открытым. Дрейн не говорит «убей». Дрейн говорит: закрой.':
    'It guards nothing and strikes no one first — it holds the rift open. Drayne does not say kill it. Drayne says: close it.',
  'Охота: ': 'Hunt: ',
  'Ловчий': 'Hunter',
  'Стихийник: ': 'Elementalist: ',
  'Глубина: этаж ': 'Depth: floor ',
  'Голова: ': 'Bounty: ',
  'Заказ кузни': 'Forge Order',
  'Поставка: ': 'Delivery: ',
  'выполнено': 'done',
  'не посещено': 'not visited',
  'этаж ': 'floor ',

  // ───────────────────────────────── меню (menus.js)
  'Инвентарь': 'Pack',
  'Герой': 'Hero',
  'Карта': 'Map',
  'Стихии': 'Elements',
  'Записи': 'Notes',
  'Продолжить': 'Continue',
  'Сохранить игру': 'Save game',
  'Настройки': 'Settings',
  'Выйти в меню': 'Quit to menu',
  'ВЫБРОСИТЬ?': 'DROP IT?',
  'Предмет пропадёт насовсем.': 'The item is gone for good.',
  'Выброшено: ': 'Dropped: ',
  'Выбросить': 'Drop',
  'Да': 'Yes',
  'Отмена': 'Cancel',
  'Esc или ПКМ — отмена': 'Esc or RMB — cancel',
  'Игра сохранена': 'Game saved',
  'ESC — закрыть': 'ESC — close',
  'Здесь остаётся всё, что игра успела объяснить.':
    'Everything the game has explained so far stays here.',
  'Пока пусто. Записи появляются сами, когда встретишь новое.':
    'Empty for now. Notes appear on their own when you meet something new.',
  'МЕТКИ': 'MARKS',
  'Вешаются умениями и аффиксами снаряжения.': 'Applied by skills and by gear affixes.',
  'РЕАКЦИИ': 'REACTIONS',
  'Вторая метка не копится поверх первой — они схлопываются в реакцию.':
    'The second mark does not stack on the first — they collapse into a reaction.',
  'тяжёлый удар': 'a heavy hit',
  'Разряд добавляет цели +22% получаемого урона, разъедание — ещё +30%.':
    'Shock adds +22% damage taken, corrosion another +30%.',
  'Руны Пирокинез, Ледяное сердце, Токсиколог, Катализатор и Резонанс читают эти метки.':
    'The runes Pyrokinesis, Frozen Heart, Toxicologist, Catalyst and Resonance read these marks.',
  'СНАРЯЖЕНИЕ': 'GEAR',
  'Снято: ': 'Unequipped: ',
  'РУНЫ УМЕНИЙ': 'SKILL RUNES',
  'пасс.': 'pass.',
  'ЛКМ — надеть / выпить  ·  ПКМ — выбросить  ·  наведи для сравнения':
    'LMB — equip / drink  ·  RMB — drop  ·  hover to compare',
  'Продать — у торговца в Велории.': 'Selling is done at a merchant in Veloria.',
  'Материал — нужен для заданий': 'Material — needed for quests',
  'Надето: ': 'Equipped: ',
  'ХАРАКТЕРИСТИКИ': 'ATTRIBUTES',
  'урон оружием': 'weapon damage',
  'Выносливость': 'Endurance',
  'здоровье и защита': 'health and defense',
  'скорость и крит': 'speed and crit',
  'мана и магия': 'mana and magic',
  'Нажимай «+», чтобы вложить': 'Press “+” to spend',
  'Очки развития дают новые уровни': 'New levels grant attribute points',
  'В БОЮ': 'IN COMBAT',
  'Крит. шанс': 'Crit chance',
  'Крит. урон': 'Crit damage',
  'Скорость': 'Speed',
  'Скор. атаки': 'Attack rate',
  'Вампиризм': 'Lifesteal',
  'КОМПЛЕКТЫ': 'SETS',
  'ЛЕТОПИСЬ': 'CHRONICLE',
  'Убито врагов': 'Enemies slain',
  'Глубина катакомб': 'Catacomb depth',
  ' эт.': ' fl.',
  'Боссов повержено': 'Bosses felled',
  'Нанесено урона': 'Damage dealt',
  'ЖУРНАЛ ЗАДАНИЙ': 'QUEST LOG',
  'Заданий нет. Поговори с капитаном Дрейном в гильдии.':
    'No quests. Speak with Captain Drayne at the guild.',
  'сдано': 'turned in',
  'доступно': 'available',
  'Прогресс: ': 'Progress: ',
  'НАГРАДА': 'REWARD',
  'оружие': 'weapon',
  'доспех': 'armor',
  'шлем': 'helm',
  'украшение': 'trinket',
  'предмет': 'item',
  'Принять': 'Accept',
  'Сдать задание': 'Turn in',
  'Задание в работе': 'Quest in progress',
  'ЛЕГЕНДА': 'LEGEND',
  'ты': 'you',
  'портал в город': 'portal to the city',
  'переход': 'exit',
  'спуск': 'descent',
  'сундук': 'chest',
  'босс': 'boss',
  'враг': 'enemy',
  'ЗОНА': 'ZONE',
  'Купить': 'Buy',
  'Продать': 'Sell',
  'ESC — уйти': 'ESC — leave',
  'з': 'g',
  'Цена:': 'Price:',
  'Продать за:': 'Sell for:',
  'Товар закончился.': 'Out of stock.',
  'Нечего продавать.': 'Nothing to sell.',
  'Выбери дверь — условия этажа изменить будет нельзя':
    'Choose a door — the floor’s terms cannot be changed later',
  'награда без изменений': 'reward unchanged',
  'Модификатор — на этаж. Порча растёт с глубиной и не снимается.':
    'The modifier lasts the floor. Corruption grows with depth and cannot be lifted.',
  'Модификатор действует только на этом этаже': 'The modifier applies to this floor only',
  'ПОЛУЧИШЬ': 'YOU GAIN',
  'ОТДАШЬ': 'YOU GIVE',
  'Отказаться': 'Decline',
  'КУЗНЯ БОРИНА': 'BORIN’S FORGE',
  'Ковка': 'Forge',
  'Заточка': 'Sharpen',
  'Переплавка': 'Reforge',
  'Разбор': 'Salvage',
  'Ковка не даёт уникальных свойств — их находят или берут заточкой на +7.':
    'Forging grants no unique properties — those are found, or taken by sharpening to +7.',
  'Пока нечего ковать — расти в уровне.': 'Nothing to forge yet — gain levels.',
  'Ковать': 'Forge it',
  'Надень оружие — точить будем его.': 'Equip a weapon — that is what we sharpen.',
  'ТОПЛИВО ×3': 'FUEL ×3',
  'ШАНС УСПЕХА': 'CHANCE',
  'ЦЕНА': 'PRICE',
  ' зол.': ' g',
  'ВЕХИ ЗАТОЧКИ': 'SHARPENING MILESTONES',
  'аффикс': 'affix',
  'свойство': 'property',
  'с редкого': 'rare and up',
  'Все вехи взяты.': 'Every milestone is taken.',
  'Веха +7 открыта только редкому оружию и выше.':
    'Milestone +7 is open only to rare weapons and better.',
  'Топливо сгорает в любом случае.': 'The fuel burns either way.',
  'При неудаче сгорает всё: и топливо, и само оружие.':
    'On a failure everything burns: the fuel and the weapon itself.',
  'Дальше некуда': 'No further',
  'ТОЧНО? ЖМИ ЕЩЁ РАЗ': 'SURE? PRESS AGAIN',
  'Заточить': 'Sharpen it',
  'Разбор превращает вещь в материалы. Вещь пропадает.':
    'Salvaging turns an item into materials. The item is gone.',
  'Переплавка бросает аффиксы заново. Ранг и редкость сохраняются.':
    'Reforging rerolls the affixes. Tier and rarity are kept.',
  'В рюкзаке нет снаряжения.': 'No gear in the pack.',
  'Разобрать': 'Salvage it',
  'Переплавить': 'Reforge it',
  'СЛИЯНИЕ РУН': 'RUNE FUSION',
  'Три одинаковые руны → одна рангом выше': 'Three identical runes → one of the next tier',
  'Одинаковых рун пока нет.': 'No matching runes yet.',
  'Дубликаты падают с элиты и боссов — не продавай их.':
    'Duplicates drop from elites and bosses — do not sell them.',
  'Слить': 'Fuse',
  'ВРАТА ВЕЛОРИИ': 'GATES OF VELORIA',
  'Открытые дороги': 'Open roads',
  'ПАУЗА': 'PAUSED',
  'Управление: WASD · ЛКМ удар · ПКМ рывок · F умение · Q зелье · E действие':
    'Controls: WASD · LMB hit · RMB dash · F skill · Q potion · E interact',
  'ТЫ ПАЛ': 'YOU FELL',
  'Возродиться в Велории': 'Revive in Veloria',
  'Новая игра': 'New game',
  'Начать путь': 'Begin the road',
  'WASD — движение · ЛКМ — удар · ПКМ — рывок · F — умение · E — действие':
    'WASD — move · LMB — hit · RMB — dash · F — skill · E — interact',
  'НАСТРОЙКИ': 'SETTINGS',
  'Громкость': 'Volume',
  'выкл': 'off',
  'Включить звук': 'Unmute',
  'Заглушить': 'Mute',
  'Экран': 'Screen',
  'Выйти из полного экрана': 'Leave fullscreen',
  'Во весь экран': 'Fullscreen',
  'Назад': 'Back',
  '← → — громкость': '← → — volume',
  'Esc — назад': 'Esc — back',
  'к л и н о к   и   г л у б и н а': 'a  b l a d e  a n d  a  d e p t h',
  'урон ': 'dmg ',
  'защита ': 'def ',
  'крит ': 'crit ',

  // ───────────────────────────────── карточка предмета (widgets.js)
  'Закалка: ': 'Tempering: ',
  'зелье': 'potion',
  'материал': 'material',
  'свиток': 'scroll',
  'пассивная руна': 'passive rune',
  'руна умения': 'skill rune',
  ' · ур. ': ' · lv. ',
  'Откат': 'Cooldown',
  ' с': 's',
  '2 части: ': '2 pieces: ',
  '4 части: ': '4 pieces: ',
  'Требуется уровень ': 'Requires level ',

  // ───────────────────────────────── мир (biomes.js, city.js, zone.js, dungeon.js)
  'Велория': 'Veloria',
  'вольный город': 'free city',
  'Изумрудный лес': 'Emerald Wood',
  'опасность: низкая': 'danger: low',
  'Пепельная топь': 'Ashen Marsh',
  'опасность: средняя': 'danger: moderate',
  'опасность: высокая': 'danger: high',
  'опасность: смертельная': 'danger: lethal',
  'Катакомбы Велории': 'Catacombs of Veloria',
  'глубина решает всё': 'depth decides everything',
  'Бездна': 'The Abyss',

  'Кузнец Борин': 'Borin the Smith',
  'оружейных дел мастер': 'master of arms',
  'Металл не врёт, парень. Врут только те, кто им торгует… но я честный.':
    'Metal does not lie, lad. Only the ones selling it do… but I am honest.',
  'Принеси руду — выкую что-нибудь стоящее. А пока бери, что есть.':
    'Bring me ore and I will forge something worth carrying. For now, take what is on the rack.',
  'Клинок тупится не о шкуру, а о нерешительность.':
    'A blade is not dulled by hide. It is dulled by hesitation.',
  'Точить берусь, но металл иногда не выдерживает. Уговор такой: рискуешь ты.':
    'I will sharpen it, but metal gives sometimes. The deal is this: the risk is yours.',
  'Оружейница Мира': 'Mira the Armorer',
  'доспехи и обереги': 'armor and charms',
  'Живой герой лучше красивого. Бери броню, а не побрякушки… хотя побрякушки тоже есть.':
    'A living hero beats a handsome one. Take armor, not trinkets… though I have trinkets too.',
  'В Мёрзлом кряже без тёплой стали делать нечего.':
    'On the Frozen Ridge there is nothing to do without warm steel.',
  'Алхимик Сельвин': 'Selvin the Alchemist',
  'зелья и настойки': 'potions and tinctures',
  'Всё есть яд, и всё есть лекарство. Вопрос лишь в цене… и цена вот такая.':
    'Everything is poison and everything is medicine. Only the price differs… and here is the price.',
  'Свиток возврата спас больше жизней, чем весь городской гарнизон.':
    'The scroll of return has saved more lives than the whole city garrison.',
  'Мастер Кален': 'Master Kalen',
  'наставник': 'trainer',
  'Сила растёт не от ударов, а от того, что ты после них встаёшь.':
    'Strength does not grow from blows. It grows from standing up after them.',
  'Есть очки развития? Вкладывай. Мёртвым они ни к чему.':
    'Got attribute points? Spend them. The dead have no use for them.',
  'Капитан Дрейн': 'Captain Drayne',
  'гильдия искателей': 'seekers’ guild',
  'Велория держится, пока кто-то ходит за её стены. Сегодня это ты.':
    'Veloria holds as long as someone walks beyond its walls. Today that is you.',
  'Задания на доске. Награда — золотом и уважением. Уважение бесплатно.':
    'The jobs are on the board. Payment is gold and respect. The respect is free.',
  'Рунная ткачиха Сивилла': 'Sibylla the Runeweaver',
  'руны умений': 'skill runes',
  'Умение живёт в камне, а не в руке. Вставь руну — и рука вспомнит, что делать.':
    'A skill lives in the stone, not the hand. Socket the rune and the hand will remember.',
  'Три знака сразу носить можно. Четвёртый — тот, что молчит и работает всегда.':
    'Three signs can be worn at once. The fourth is the one that stays quiet and always works.',
  'Не бывает плохих рун. Бывают вставленные не в тот бой.':
    'There are no bad runes. Only runes socketed for the wrong fight.',
  'Хранитель врат Азель': 'Azel the Gatekeeper',
  'смотритель порталов': 'warden of portals',
  'Врата помнят каждого, кто прошёл. И не всех возвращают.':
    'The gates remember everyone who passed. They do not return all of them.',
  'Открытые дороги — те, что по силам. Остальные подождут твоего роста.':
    'The open roads are the ones within your strength. The rest will wait for you to grow.',

  'Древние руины': 'Ancient Ruins',
  'Разбойничий лагерь': 'Bandit Camp',
  'Логово вожака': 'Chieftain’s Den',
  'Бродячий торговец Хальд': 'Hald the Wandering Trader',
  'редкости из дальних мест': 'rarities from far places',
  'Дороги опасны, зато цены честные. Почти.':
    'The roads are dangerous, but my prices are fair. Almost.',
  'Товар редкий: что было по пути, то и есть.':
    'The stock is thin: what I found on the road is what there is.',
  'Стоянка торговца': 'Trader’s Camp',
  'Спуститься в катакомбы': 'Descend into the catacombs',
  'Вернуться в Велорию': 'Return to Veloria',

  // ───────────────────────────────── образцы со вставленными числами
  //
  // `{n}` — место числа. Порядок меток можно менять: «{0} из {1}» → «{1} in {0}»
  // законно, если так правильнее по-английски.
  'Врата не пускают: нужен уровень {0}': 'The gate refuses you: level {0} required',
  'ЭТАЖ {0}': 'FLOOR {0}',
  '{0} · уровень мобов ~{1}': '{0} · enemy level ~{1}',
  '+{0} опыта': '+{0} XP',
  'Нужен уровень {0}': 'Level {0} required',
  ', +{0} зол.': ', +{0} g',
  '+{0} очков развития (клавиша C)': '+{0} attribute points (key C)',
  '+{0} опыта, +{1} золота': '+{0} XP, +{1} gold',
  'Развитие ({0})': 'Attributes ({0})',
  'Очки сброшены: {0} доступно': 'Points reset: {0} available',
  'Задание принято: ': 'Quest accepted: ',
  'Готово к сдаче: ': 'Ready to turn in: ',
  '{0}/{1} этаж': 'floor {0}/{1}',
  'Торговец дал бы за него {0} зол.': 'A merchant would pay {0} g for it.',
  'Выбросить ×{0}': 'Drop ×{0}',
  'ЗАПИСИ · {0} из {1}': 'NOTES · {0} of {1}',
  'Мощь: {0}': 'Power: {0}',
  'Урон {0}   Защита {1}': 'Damage {0}   Defense {1}',
  'Крит {0}%   Сниж.урона {1}%': 'Crit {0}%   Dmg red. {1}%',
  'РЮКЗАК  {0}/{1}': 'PACK  {0}/{1}',
  'РЮКЗАК': 'PACK',
  'Уровень мобов': 'Enemy level',
  'Врагов': 'Enemies',
  // указатель цели: приставки-«головы» — хвост переводится сам
  'Взять: ': 'Take: ',
  'Сдать: ': 'Turn in: ',
  'В Велорию: ': 'To Veloria: ',
  'В Велорию — есть задание': 'To Veloria — a quest awaits',
  // пустые списки в кузне
  'Разбирают лишние вещи — сначала их надо найти.': 'Salvage needs spare gear — go find some first.',
  'Переплавляют уже найденное — сходи в подземелье.': 'Reforging needs gear you already own — head underground.',
  'Пока нечего ковать.': 'Nothing to forge yet.',
  'Рецепты открываются с уровнем героя.': 'Recipes unlock as you level up.',
  'Загляни позже — запас пополнится.': 'Come back later — stock will refill.',
  'Хлам из подземелья продают здесь.': 'Dungeon junk gets sold right here.',
  // вход через кошелёк
  'Войти через Phantom': 'Sign in with Phantom',
  'Установить Phantom': 'Install Phantom',
  'Играть гостем': 'Play as guest',
  'Гость': 'Guest',
  'Выйти': 'Sign out',
  'Подключаем кошелёк…': 'Connecting wallet…',
  'Подтверди вход в окне Phantom': 'Confirm the sign-in in Phantom',
  'Подпись подтверждает вход и не переводит средства': 'The signature confirms sign-in and moves no funds',
  'Кошелька Phantom не видно — можно играть гостем': 'No Phantom wallet found — you can play as guest',
  'Кошелёк Phantom не найден': 'Phantom wallet not found',
  'Не удалось войти через кошелёк': 'Wallet sign-in failed',
  'Игра никогда не спросит seed-фразу и не попросит подтвердить перевод': 'This game never asks for a seed phrase and never requests a transfer',
  'Этаж': 'Floor',
  'ур. {0} · берегись': 'lv. {0} · beware',
  'Карта': 'Map',
  'ИТОГ': 'TOTAL',
  'Сниж. урона': 'Dmg reduction',
  'Мощь {0}': 'Power {0}',
  '{0} / {1}': '{0} / {1}',
  '{0} зол.': '{0} g',
  'Свободных очков развития: {0}': 'Unspent attribute points: {0}',
  '{0}  (−{1}% урона)': '{0}  (−{1}% damage)',
  '{0}/сек': '{0}/s',
  'Опыт {0} / {1}': 'XP {0} / {1}',
  'уровень {0}': 'level {0}',
  'Уровень {0}  ·  ': 'Level {0}  ·  ',
  '{0} опыта': '{0} XP',
  '{0} золота': '{0} gold',
  'предмет ×{0}': 'item ×{0}',
  'Уровень мобов ~{0}': 'Enemy level ~{0}',
  'Этаж {0}': 'Floor {0}',
  'Врагов: {0}': 'Enemies: {0}',
  'БЕЗДНА · ЭТАЖ {0}': 'ABYSS · FLOOR {0}',
  'СПУСК НА ЭТАЖ {0}': 'DESCEND TO FLOOR {0}',
  'рекорд глубины: {0}': 'depth record: {0}',
  'награда +{0}%': 'reward +{0}%',
  'награда {0}%': 'reward {0}%',
  ' (есть {0})': ' (have {0})',
  'ур. {0}': 'lv. {0}',
  'при удаче: +{0}% к характеристикам': 'on success: +{0}% to stats',
  'Следующая заточка — веха: ': 'Next sharpening is a milestone: ',
  'До ближайшей вехи ещё {0} уровня заточки.': '{0} more sharpening levels to the next milestone.',
  'Оружие уцелеет: при неудаче откатится к вехе +{0}.':
    'The weapon survives: a failure rolls it back to milestone +{0}.',
  'Вехи ещё нет — откатываться некуда. С +{0} оружие уже не гибнет.':
    'No milestone yet — nothing to roll back to. From +{0} on, the weapon no longer dies.',
  'требуется уровень {0}': 'requires level {0}',
  'ур. {0}–{1}': 'lv. {0}–{1}',
  'рекорд: {0} эт.': 'record: {0} fl.',
  'Уровень {0}  ·  убито врагов: {1}': 'Level {0}  ·  enemies slain: {1}',
  'Потеряно золота: {0}': 'Gold lost: {0}',
  'БЕЗДНА · {0}': 'ABYSS · {0}',
  'ГЛУБИНА · {0}': 'DEPTH · {0}',
  'Бездна · этаж {0}': 'Abyss · floor {0}',
  'Катакомбы · этаж {0}': 'Catacombs · floor {0}',
  'Спуститься на этаж {0}': 'Descend to floor {0}',
  'Гильдия платит за головы. Цель — ': 'The guild pays for heads. Target — ',
  'Вожаки и элита ходят под аффиксами и бьют иначе. Гильдии нужно {0} таких голов — где возьмёшь, дело твоё.':
    'Chieftains and elites carry affixes and fight differently. The guild wants {0} such heads — where you find them is your business.',
  'Алхимики гильдии платят за наблюдения. Вызови реакцию «': 'The guild alchemists pay for observations. Trigger the reaction “',
  'В катакомбах пропала разведка. Спустись до {0}-го этажа и вернись — этого хватит.':
    'A scouting party vanished in the catacombs. Reach floor {0} and come back — that will do.',
  'Борину нужны руки. Выкуй {0} вещи любого вида — гильдия оплатит материалы сверху.':
    'Borin needs hands. Forge {0} items of any kind — the guild covers the materials on top.',
  'Склад гильдии пуст. Принеси {0} ед. — «': 'The guild store is empty. Bring {0} units — “',

  // образцы описаний контрактов: {a}/{b} — имена, {n} — счёт
  'Гильдия платит за головы. Цель — {a} ({b}), {n} шт.':
    'The guild pays for heads. Target — {a} ({b}), {n} of them.',
  'Вожаки и элита ходят под аффиксами и бьют иначе. Гильдии нужно {n} таких голов — где возьмёшь, дело твоё.':
    'Chieftains and elites carry affixes and fight differently. The guild wants {n} such heads — where you find them is your business.',
  'Алхимики гильдии платят за наблюдения. Вызови реакцию «{a}» {n} раз.':
    'The guild alchemists pay for observations. Trigger the “{a}” reaction {n} times.',
  'В катакомбах пропала разведка. Спустись до {n}-го этажа и вернись — этого хватит.':
    'A scouting party vanished in the catacombs. Reach floor {n} and come back — that will do.',
  '{a} снова поднялся в {b}. Гильдия закрывает вопрос.':
    '{a} has risen again in the {b}. The guild is closing the matter.',
  'Борину нужны руки. Выкуй {n} вещи любого вида — гильдия оплатит материалы сверху.':
    'Borin needs hands. Forge {n} items of any kind — the guild covers the materials on top.',
  'Склад гильдии пуст. Принеси {n} ед. — «{a}».':
    'The guild store is empty. Bring {n} units of “{a}”.',

  // прочие склейки с именами
  'уровень мобов ~{0}': 'enemy level ~{0}',
  '{a} призывает подмогу!': '{a} calls for help!',
  'заточка +{0} из {1}': 'sharpening +{0} of {1}',
  'оружие редкости «{a}»': 'a weapon of “{a}” rarity',

  // ── заточка: ручной выбор топлива
  'ТВОЁ ОРУЖИЕ': 'YOUR WEAPONS',
  'годится только редкость «{a}»': 'only “{a}” weapons fit',
  'Авто': 'Auto',
  'Тащи сюда или щёлкни — вещь сгорит.': 'Drag here or click — it burns.',
  'Нет подходящего оружия.': 'No weapon fits.',
  'Нужна та же редкость.': 'Same rarity is required.',
  'Топливо изменилось — выбери заново': 'The fuel changed — pick again',
  'Следующая заточка — веха: {a}.': 'The next sharpening is a milestone: {a}.',
  'Сбой:\n': 'Crash:\n',

  // строчные формы: интерфейс кое-где опускает регистр
  'горение': 'burning',
  'обморожение': 'chill',
  'отравление': 'poisoned',
  'разряд': 'shock',
  'ослепление': 'blinded',
  'разъедание': 'corrosion',
  'проводимость': 'conduction',
  'пар': 'steam',
  'раскол': 'shatter',
  '{0} эт.': '{0} fl.',
  '{0}з': '{0}g',
  '{0} с': '{0}s',
  ' (есть {0})': ' (have {0})',
};
